export default {
  routes: [
    {
      method: 'GET',
      path: '/analisis/concordancias',
      handler: 'analisis.concordancias',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/estilometria',
      handler: 'analisis.estilometria',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/innovacion',
      handler: 'analisis.innovacion',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/analisis/interpretar-deriva',
      handler: 'analisis.interpretarDeriva',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/cadenas-lexicas',
      handler: 'analisis.cadenasLexicas',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/nube-palabras-autor',
      handler: 'analisis.nubePalabrasAutor',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/nube-palabras-revista',
      handler: 'analisis.nubePalabrasRevista',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/morfologica',
      handler: 'analisis.morfologica',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/publicidad/frecuencia',
      handler: 'analisis.publicidadFrecuencia',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/publicidad/tendencias',
      handler: 'analisis.publicidadTendencias',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/publicidad/categorias',
      handler: 'analisis.listarCategorias',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/analisis/publicidad/descubrir-categorias',
      handler: 'analisis.descubrirCategorias',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/analisis/publicidad/guardar-categorias',
      handler: 'analisis.guardarCategorias',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/analisis/publicidad/toggle-categoria',
      handler: 'analisis.toggleCategoria',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/publicidad/publicaciones',
      handler: 'analisis.publicidadPublicaciones',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/publicidad/cadenas-lexicas',
      handler: 'analisis.publicidadCadenasLexicas',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/publicidad/vanguardia',
      handler: 'analisis.publicidadVanguardia',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/validador/articulos',
      handler: 'analisis.validadorArticulos',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/analisis/validador/guardar',
      handler: 'analisis.validadorGuardar',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analisis/validador-temas/articulos',
      handler: 'analisis.validadorTemasArticulos',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/analisis/validador-temas/guardar',
      handler: 'analisis.validadorTemasGuardar',
      config: { auth: false },
    },
  ],
};
